[tool.poetry]
name = "js-ext"
packages = [{ include = "jumpscale" }]

version = "0.1.0"
description = ""
authors = ["xmonader <xmonader@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
js-ng = { git = "https://github.com/js-next/js-ng.git" }
python = "^3.6"
pdoc3 = "^0.6.3"
pytest = "^5.0"
codecov = "^2.0"
tox = "^3.13"
pytest-cov = "^2.7"
hypothesis = "^4.28"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
